services:
  db:
    image: mysql:8.0
    build: 
      context: .
      dockerfile: Database/Dockerfile
    volumes:
      - ./Database/data:/var/lib/mysql
  api:
    image: masjidapp.api.restful
    build:
      context: .
      dockerfile: MasjidApp.API.Restful/Dockerfile
    environment:
      ConnectionStrings__AuthenticationConnection: "Server=db;Database=masjidappdatabase;User=authenticationuser;Password=BL/6Fx$Ku!2{37GvPS9;"
    ports:
      - "5000:8080"

networks:
  default:
    driver: bridge

