services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: REG+~.Uqj1HYuci_0aFUht~Nk56Vh
      MYSQL_DATABASE: masjidappdatabase
      MYSQL_USER: masjidappuser
      MYSQL_PASSWORD: 2T4@Kzh,LnU+}_Cs0^ob@*VMT7V
    ports:
      - "3306:3306"
    volumes:
      - ./Database/data:/var/lib/mysql
      - ./Database/scripts:/docker-entrypoint-initdb.d/

  api:
    image: masjidapp.api.restful
    build:
      context: .
      dockerfile: MasjidApp.API.Restful/Dockerfile
    environment:
      ConnectionStrings__AuthenticationConnection: "Server=db;Database=masjidappdatabase;User=authenticationuser;Password=BL/6Fx$Ku!2{37GvPS9;"
    ports:
      - "5000:8080"

networks:
  default:
    driver: bridge

