version: '3.8'
services:
  db:
    image: zayd-mcardle/masjidapp-database
    build: 
      context: .
      dockerfile: Database/Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: REGUqj1HYuci_0aFUhtNk56Vh
    volumes:
      - ./Database/data:/var/lib/mysql
    networks:
      - masjidapp-network
  api:
    image: masjidapp.api.restful
    build:
      context: .
      dockerfile: MasjidApp.API.Restful/Dockerfile
    environment:
      ConnectionStrings__AnnouncementConnection: "Server=db;Database=masjidappdatabase;User=announcementsuser;Password=LzwvN6bU4y3EqmAYBMJFrn;"
      ConnectionStrings__AuthenticationConnection: "Server=db;Database=masjidappdatabase;User=authenticationuser;Password=BL6FxKu!237GvPS9;"
      ConnectionStrings__PrayerTimesConnection: "Server=db;Database=masjidappdatabase;User=prayertimesuser;Password=HR0o8N&Rk%wvu@Ma%IBh7yaf;"
    ports:
      - "5000:8080"
    networks:
      - masjidapp-network

networks:
  masjidapp-network:
    driver: bridge

