name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  run-backend-pipeline:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
    - uses: actions/checkout@v4
    - name: Run backend pipeline
      run: | 
	set -e
	cd Backend
	make integration-test 
